[/]
color-collection=[uint32 30396, 1710105]
color-history=[uint32 67108864, 0, 30396, 1513239, 1643797, 1775123, 1644309, 1382678]
color-picker-shortcut=['<Super>x']
custom-formats=[<{'enable': <true>, 'name': <'RGBA'>, 'format': <'rgba({Re}, {Gr}, {Bl}, {Al})'>}>, <{'enable': <true>, 'name': <'HUE'>, 'format': <'hue({Hu})'>}>]
default-format=uint32 0
enable-format=true
enable-shortcut=true
enable-sound=false
format-menu=true
menu-key='f'
preview-style=uint32 0
