[/]
active-border-radius=0
active-border-size=0
animation-duration=200
animation-enabled=false
dim-inactive=false
float-list=['re.sonny.Junction', 'org.gnome.Calculator', 'io.github.giantpinkrobots.flatsweep', 'discord', 'qalculate-gtk', 'wofi', 'MEGAsync', 'package', 'localsend_app', 'io.bassi.Amberol']
focus-pulse=false
inner-gap=3
outer-gap=0
override-minimize=@as []
resize-step=0.01
show-indicator=false
tile-close-window=@as []
tile-equalize=@as []
tile-focus-down=@as []
tile-focus-left=@as []
tile-focus-right=@as []
tile-focus-up=@as []
tile-move-down=@as []
tile-move-left=@as []
tile-move-right=@as []
tile-move-up=@as []
tile-resize-down=['<Control><Super>Down']
tile-resize-left=['<Control><Super>Left']
tile-resize-right=['<Control><Super>Right']
tile-resize-up=['<Control><Super>Up']
tile-toggle-float=['<Super>f']
tile-toggle-split=@as []
tiling-enabled=true
