[/]
app-menu-max-width=135
extend-left-box=false
greyscale-tray-icons=false
hide-activities-button='never'
hide-app-menu-icon=true
hide-window-titlebars='always'
reduce-panel-spacing=true
show-desktop-name=false
show-legacy-tray=true
show-window-buttons='always'
show-window-title='never'
use-activities-text=false
window-buttons-theme='ambiance'
